apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization

resources:
  - openpanel-rollout-api.yml
  - openpanel-rollout-worker.yml
  - openpanel-rollout-dashboard.yml

images:
  - name: ghcr.io/javierfg1/api
    newTag: latest

  - name: ghcr.io/javierfg1/worker
    newTag: latest

  - name: ghcr.io/javierfg1/dashboard
    newTag: latest