apiVersion: v1
kind: Service
metadata:
  name: openpanel-api-active
  namespace: openpanel
spec:
  selector:
    app: openpanel-api
  ports:
    - port: 8087
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: openpanel-api-preview
  namespace: openpanel
spec:
  selector:
    app: openpanel-api
  ports:
    - port: 8087 # Puerto del servicio
      targetPort: 3000 # Puerto del contenedor