  apiVersion: argoproj.io/v1alpha1
  kind: Rollout
  metadata:
    name: openpanel-api
    namespace: openpanel
    # Añadir anotaciones para que escrapear métricas
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "3000"   # 👈 puerto real del container
      prometheus.io/path: "/metrics"
  spec:
    replicas: 1
    strategy:
      blueGreen:
        activeService: openpanel-api-active
        previewService: openpanel-api-preview
        # Recibe tráfico por lo que antes de promocionar podría ser conveniente controlar que todo este bien (sería false en este caso).
        autoPromotionEnabled: true
    selector:
      matchLabels:
        app: openpanel-api
    template:
      metadata:
        labels:
          app: openpanel-api
      spec:
        containers:
          - name: openpanel-api
            image: ghcr.io/javierfg1/api
            env:
              # Una vez desplegados, hacer port forward para probar
              - name: ORACLE_USER
                valueFrom:
                    secretKeyRef:
                        name: oracle-credentials
                        key: ORACLE_USER
              - name: ORACLE_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: oracle-credentials
                        key: ORACLE_PASSWORD
              - name: DATABASE_URL
                value: postgresql://$(ORACLE_USER):$(ORACLE_PASSWORD)@op-db:5432/postgres
              - name: REDIS_URL
                value: redis://op-kv:6379
            # Puerto igual al de dashboard. No hay conflicto porque son distintos pods.
            ports:
              - containerPort: 3000
