apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openpanel
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: openpanel-api=ghcr.io/javierfg1/api, openpanel-worker=ghcr.io/javierfg1/worker, openpanel-dashboard=ghcr.io/javierfg1/dashboard
    argocd-image-updater.argoproj.io/openpanel-api.update-strategy: semver
    argocd-image-updater.argoproj.io/openpanel-worker.update-strategy: semver
    argocd-image-updater.argoproj.io/openpanel-dashboard.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: plain
spec:
  destination:
    name: in-cluster
    namespace: openpanel
  source:
    path: manifests
    repoURL: https://github.com/javierfg1/openpanel-app.git
    targetRevision: staging
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true