apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: openpanel-updater
  namespace: argocd
spec:

  # 🔧 defaults globales
  #commonUpdateSettings:
  #  updateStrategy: latest
  #  allowTags: ".*"
  #  pullSecret: ghcr-creds

  # 🔧 cómo escribir cambios
  writeBackConfig:
    method: argocd

  applicationRefs:
    - namePattern: "openpanel"

      # puedes usar labels en vez de namePattern si quieres
      # labelSelectors:
      #   matchLabels:
      #     app.kubernetes.io/name: openpanel

      commonUpdateSettings:
        updateStrategy: semver

      images:
        - alias: api
          imageName: ghcr.io/javierfg1/api

          manifestTargets:
            kustomize:
              name: ghcr.io/javierfg1/api

        - alias: dashboard
          imageName: ghcr.io/javierfg1/dashboard

          manifestTargets:
            kustomize:
              name: ghcr.io/javierfg1/dashboard

        - alias: worker
          imageName: ghcr.io/javierfg1/worker

          manifestTargets:
            kustomize:
              name: ghcr.io/javierfg1/worker