apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: openpanel-worker
  namespace: openpanel
# Añadir anotaciones para que escrapear métricas
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"   # 👈 puerto real del container
    prometheus.io/path: "/metrics"
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: openpanel-worker-active
      previewService: openpanel-worker-preview
      # Lo ponemos a true porque no recibe ttráfico
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: openpanel-worker
  template:
    metadata:
      labels:
        app: openpanel-worker
    spec:
      containers:
        - name: openpanel-worker
          image: ghcr.io/javierfg1/worker
          # Puerto para métricas
          ports:
            - containerPort: 9090