apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: openpanel-updater
  namespace: argocd
spec:

  
  # 🔧 cómo escribir cambios (no modificamos github rollouts, sino que comunicamos directamente a Argo CD los cambios para que despliegue)
  writeBackConfig:
    method: argocd

  applicationRefs:
    - namePattern: "openpanel"

      commonUpdateSettings:
        updateStrategy: semver
        pullSecret: ghcr-creds

      images:
        - alias: api
          imageName: ghcr.io/javierfg1/api

          manifestTargets:
            kustomize:
              name: ghcr.io/javierfg1/api

        - alias: dashboard
          imageName: ghcr.io/javierfg1/dashboard

          manifestTargets:
            kustomize:
              name: ghcr.io/javierfg1/dashboard

        - alias: worker
          imageName: ghcr.io/javierfg1/worker

          manifestTargets:
            kustomize:
              name: ghcr.io/javierfg1/worker