name: Docker OpenPanel Build and Push

on:
  workflow_dispatch:
  push:
    # Push de las dos ramas.
    branches: [ "main", "staging" ]
    # El workflow solo se ejecutará si se modifica alguno de los archivos que están en paths.
    paths:
      - "apps/api/**"
      - "apps/worker/**"
      - "apps/public/**"
      - "apps/start/**"
      - "packages/**"
      - "!packages/sdks/**"
      - "**Dockerfile"
      - ".github/workflows/**"

env:
  repo_owner: "javierfg1"

jobs:
  changes:
    runs-on: self-hosted
    # Expone el resultado del filtro como variables booleanas, es decir, 
    # podremos hacer buils selectivos porque sabremos que servicios han sido modificados (evita builds innecesarios)
    # Ejemplo uso posterior --> needs.changes.outputs.api == 'true'
    outputs:
      api: ${{ steps.filter.outputs.api }}
      worker: ${{ steps.filter.outputs.worker }}
      public: ${{ steps.filter.outputs.public }}
      dashboard: ${{ steps.filter.outputs.dashboard }}
    steps:
      - uses: actions/checkout@v4
      # Analiza los cambios del commit y decide que servicios han sido modificados
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # Rama con la que comparar (main,staging) el commit actual
          #base: "main"
          base: "staging"
          filters: |
            api:
              - 'apps/api/**'
              - 'packages/**'
              - '.github/workflows/**'
            worker:
              - 'apps/worker/**'
              - 'packages/**'
              - '.github/workflows/**'
            public:
              - 'apps/public/**'
              - 'packages/**'
              - '.github/workflows/**'
            dashboard:
              - 'apps/start/**'
              - 'packages/**'
              - '.github/workflows/**'

  lint-and-test:
    # Este job depende del job "changes".
    # Needs conecta jobs
    # [STEP] steps.filter.outputs.api --> [JOB OUTPUT] changes.outputs.api --> [OTRO JOB] needs.changes.outputs.api
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' || needs.changes.outputs.worker == 'true' || needs.changes.outputs.public == 'true' || needs.changes.outputs.dashboard == 'true' }}
    runs-on: self-hosted
    # Levanta servicios Redis
    # Es un Redis temporal, usado para probar el código. Una vez terminado, destruye el contenedor.
    # En el argo rollout, definiremos el redis que ya hay corriendo en el cluster kubernetes (REDIS_URL).
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 20
    # Preparar el entorno y deja lista la aplicación para:
    #     Instalar dependencias
    #     Generar código
    #     Ejecutar lint / tests
    steps:
      # Clona repositorio en el runner.
      - uses: actions/checkout@v4

      # Requerido para ejecutar pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Instala la versión de pnpm que se indica en package.json
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Calcula dónde pnpm guarda dependencias y pone la ruta en STORE_PATH,
      # que podrá ser referenciada posteriormente.
      # (STORE_PATH se guarda en el archivo temporal GITHUB_ENV que se crea en el runner)
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # Guarda dependencias entre ejecuciones..
      #- name: Setup pnpm cache
      #  uses: actions/cache@v3
      #  # Aceleramos el proceso de CI porque, si no cambia pnpm-lock.yaml, lo reutiliza.
      #  with:
      #    path: ${{ env.STORE_PATH }}
      #    key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #    restore-keys: |
      #      ${{ runner.os }}-pnpm-store-

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      # Instala apps, packages, dependencias internas.
      - name: Install dependencies
        run: pnpm install

      # Generación de código automática antes de tests/build
      # Los scripts están en package.json. En este caso, se ejecutará --> pnpm -r --filter db --filter geo run codegen
      - name: Codegen
        run: pnpm codegen


      # Después de la priemera ejecución, probaremos los tres pasos siguientes.

      # Ejecutamos el linter Biome para validar el estilo del código
      #- name: Run Biome
      #  run: pnpm lint

      # Ejecuta --> pnpm -r --no-bail typecheck
      # Ejecuta el script llamado "typecheck" que cada paquete tenga en su propio package.json. 
      # Normalmente, ese script suele ser tsc --noEmit (comprobar tipos sin generar archivos .js).
      #- name: Run TypeScript checks
      #  run: pnpm typecheck

      # Ejecuta --> vitest run
      # Tests unitarios en test.ts
      #- name: Run tests
      #  run: pnpm test

  # Este job:
  #   Construye la imagen Docker del API
  #   La sube a un registry (GHCR)
  #   Etiqueta la versión
  #   Solo se ejecuta si cambia el API
  build-and-push-api:
    #Permisos necesarios para subir imágenes a registry y crear tags en git.
    permissions:
      packages: write
      contents: write
    # Depende de los  jobs "changes" y "lint-and-test".
    needs: [changes, lint-and-test]
    # Solo se ejecuta si se ha modificado api.
    if: ${{ needs.changes.outputs.api == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Se generan tags dinámicos, se guardan en GITHUB_OUTPUT, y se referencian como "steps.tags.outputs.branch_name".
      #- name: Generate tags
      #  id: tags
      #  run: |
      #    # Sanitize branch name by replacing / with -
      #    BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
      #    # Get first 4 characters of commit SHA
      #    SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-4)
      #    echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      #    echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      # Aplicamos estrategia semver, obtenemos la última versión de git
      # Referencia "steps.version.outputs.version"
      - name: Get version
        id: version
        run: |
          git fetch --tags

          # Si no hay tag, versión base
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.1.0")

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Habilita builds avanzados, cache, multi-platform
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # servicio de GitHub diseñado para alojar y gestionar imágenes de Docker (contenedores) directamente en tu cuenta 
      # u organización, de forma similar a como lo hace Docker Hub.
      # github.actor --> Variable automática del contexto de GitHub Actions. La define GitHub Actions.
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # "context: ." indica que se usa todo el repositorio.
      # Usa el DOckerfile de API.
      # Genera tags trazables, únicos por commit.
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          #tags: |
            #ghcr.io/${{ env.repo_owner }}/api:${{ steps.tags.outputs.branch_name }}-${{ steps.tags.outputs.short_sha }}
          tags: |
            ghcr.io/${{ env.repo_owner }}/api:${{ steps.version.outputs.version }}
          build-args: |
            DATABASE_URL=postgresql://postgres:postgres@op-db:5432/postgres

      # Actualiza el tag en la rama main para marcar la última versión desplegada.
      # En la propuesta, plantemao usar ArgoCD Image Updater, pero, de momento, dejamos la opción por defecto de este workflow
      # Es necesario para integración con CD, es una referencia para ArgoCD.
      # - name: Create/Update API tag
      #  if: github.ref == 'refs/heads/main'
      #  run: |
      #    # Delete existing tag if it exists
      #    if git tag -l "api" | grep -q "api"; then
      #      git tag -d "api"
      #      echo "Deleted local tag: api"
      #    fi

      #    # Create new tag
      #    git tag "api" "${{ github.sha }}"
      #    echo "Created tag: api"

          # Push tag to remote
      #    git push origin "api" --force
      #    echo "Pushed tag: api".

      - name: Bump version
        id: bump
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          echo "Current version: $VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          PATCH=$((PATCH + 1))

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          echo "New version: $NEW_VERSION"

          git tag "$NEW_VERSION"
          git push origin "$NEW_VERSION"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

  build-and-push-worker:
    permissions:
      packages: write
      contents: write
    needs: [changes, lint-and-test]
    if: ${{ needs.changes.outputs.worker == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Generate tags
      #  id: tags
      #  run: |
      #    # Sanitize branch name by replacing / with -
      #    BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
      #    # Get first 4 characters of commit SHA
      #    SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-4)
      #    echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      #    echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
      
      # Aplicamos estrategia semver, obtenemos la versión de git.
      - name: Get version
        id: version
        run: |
          git fetch --tags

          # Si no hay tag, versión base
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.1.0")

          echo "version=$VERSION" >> $GITHUB_OUTPUT
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/worker/Dockerfile
          push: true
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          #tags: |
          #  ghcr.io/${{ env.repo_owner }}/worker:${{ steps.tags.outputs.branch_name }}-${{ steps.tags.outputs.short_sha }}
          tags: |
            ghcr.io/${{ env.repo_owner }}/worker:${{ steps.version.outputs.version }}
          build-args: |
            DATABASE_URL=postgresql://postgres:postgres@op-db:5432/postgres

      #- name: Create/Update Worker tag
      #  if: github.ref == 'refs/heads/main'
      #  run: |
      #    # Delete existing tag if it exists
      #    if git tag -l "worker" | grep -q "worker"; then
      #      git tag -d "worker"
      #      echo "Deleted local tag: worker"
      #    fi

      #    # Create new tag
      #    git tag "worker" "${{ github.sha }}"
      #    echo "Created tag: worker"

          # Push tag to remote
      #    git push origin "worker" --force
      #    echo "Pushed tag: worker"

      - name: Bump version
        id: bump
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          echo "Current version: $VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          PATCH=$((PATCH + 1))

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          echo "New version: $NEW_VERSION"

          git tag "$NEW_VERSION"
          git push origin "$NEW_VERSION"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT      
          

  build-and-push-dashboard:
    permissions:
      packages: write
      contents: write
    needs: [changes, lint-and-test]
    if: ${{ needs.changes.outputs.dashboard == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Generate tags
      #  id: tags
      #  run: |
      #    # Sanitize branch name by replacing / with -
      #    BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
      #    # Get first 4 characters of commit SHA
      #    SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-4)
      #    echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      #    echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      # Aplicamos estrategia semver, obtenemos la versión de git
      - name: Get version
        id: version
        run: |
          git fetch --tags

          # Si no hay tag, versión base
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.1.0")

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/start/Dockerfile
          push: true
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          #tags: |
          #  ghcr.io/${{ env.repo_owner }}/dashboard:${{ steps.tags.outputs.branch_name }}-${{ steps.tags.outputs.short_sha }}
          tags: |
            ghcr.io/${{ env.repo_owner }}/api:${{ steps.version.outputs.version }}   
          build-args: |
            NO_CLOUDFLARE=1

      #- name: Create/Update Dashboard tag
      #  if: github.ref == 'refs/heads/main'
      #  run: |
      #    # Delete existing tag if it exists
      #    if git tag -l "dashboard" | grep -q "dashboard"; then
      #      git tag -d "dashboard"
      #      echo "Deleted local tag: dashboard"
      #    fi

      #    # Create new tag
      #    git tag "dashboard" "${{ github.sha }}"
      #    echo "Created tag: dashboard"

      #    # Push tag to remote
      #    git push origin "dashboard" --force
      #    echo "Pushed tag: dashboard"
      - name: Bump version
        id: bump
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          echo "Current version: $VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          PATCH=$((PATCH + 1))

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          echo "New version: $NEW_VERSION"

          git tag "$NEW_VERSION"
          git push origin "$NEW_VERSION"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT